# Copyright (C) 2023-2026 Sebastien Rousseau.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Optional OpenTelemetry tracing + RED metrics for camt.05x workflows.

Production deployments of camt053 (CLI, REST API, MCP server, LSP
server) commonly need to surface per-operation tracing and the
classic **RED** metrics:

* **R**equests per second per operation
* **E**rrors per second per operation, broken down by kind
* **D**uration histogram per operation (p50 / p95 / p99)

This module ships the camt053-side primitives so the consumer's
collector / dashboard sees consistent span names and metric names
regardless of which interface (CLI / REST / MCP / LSP) is in use.

Optional dependency
-------------------
OpenTelemetry is **not** a runtime dependency of camt053; installing
it would bloat every install for a feature the library cannot
configure for the user. Instead, ``camt053[telemetry]`` ships the
``opentelemetry-api`` extra, and the module gracefully degrades to a
**zero-overhead no-op** when the API is absent: the public helpers
all return null-object stand-ins that swallow every method call.

That means downstream code can call :func:`trace_span` /
:func:`record_request` unconditionally — no surrounding ``if`` —
without paying for telemetry unless the operator opts in by
installing the extra and configuring a global tracer / meter
provider.

Span names + metric names
-------------------------
Stable, lowercase, dot-separated; never include user input. The
service facade emits spans / counters with these names so callers
see consistent telemetry regardless of which surface (CLI / REST /
MCP / LSP) is in use:

* **Spans**: ``camt053.parse``, ``camt053.validate``, ``camt053.reverse``.
* **Counters**: ``camt053_requests_total{op,status}``,
  ``camt053_errors_total{op,kind}``.
* **Histogram**: ``camt053_duration_seconds{op}``.

PII redaction
-------------
Span attributes never carry IBAN / BIC / name values verbatim. The
shapes that the camt053 service facade emits use redacted forms
(prefix / mask / count) generated by :mod:`camt053.logging`'s
:func:`redact_iban` / :func:`redact_bic` / :func:`redact_name`. The
:func:`safe_span_attribute` helper applies the same policy.
"""

from __future__ import annotations

import time
from contextlib import contextmanager
from typing import Any

from camt053.logging import redact_value

__all__ = [
    "SPAN_PARSE",
    "SPAN_VALIDATE",
    "SPAN_REVERSE",
    "METRIC_REQUESTS",
    "METRIC_ERRORS",
    "METRIC_DURATION",
    "is_telemetry_available",
    "get_tracer",
    "get_meter",
    "trace_span",
    "record_request",
    "record_error",
    "record_duration",
    "safe_span_attribute",
]


SPAN_PARSE = "camt053.parse"
SPAN_VALIDATE = "camt053.validate"
SPAN_REVERSE = "camt053.reverse"

METRIC_REQUESTS = "camt053_requests_total"
METRIC_ERRORS = "camt053_errors_total"
METRIC_DURATION = "camt053_duration_seconds"


# Try to import the OpenTelemetry API. Absent → use no-op stubs so
# callers do not need ``if`` guards. The runtime cost when absent is
# a one-time ImportError caught here at module load.
try:  # pragma: no cover - exercised by both branches in CI
    from opentelemetry import metrics as _otel_metrics
    from opentelemetry import trace as _otel_trace

    _OTEL_AVAILABLE = True
except ImportError:  # pragma: no cover - depends on install extras
    _otel_trace = None
    _otel_metrics = None
    _OTEL_AVAILABLE = False


def is_telemetry_available() -> bool:
    """Return ``True`` if the OpenTelemetry API is importable.

    Useful as a precondition guard for code paths that want to behave
    differently when telemetry is opt-in versus on. The library's own
    helpers are no-ops when telemetry is absent, so most callers will
    never need this check; it exists for sanity tests + diagnostics.
    """
    return _OTEL_AVAILABLE


class _NoopSpan:
    """Null-object span: every method swallows its arguments."""

    def set_attribute(self, _key: str, _value: Any) -> None:
        """Accept and discard a span attribute."""

    def set_status(self, _status: Any, _description: str = "") -> None:
        """Accept and discard a status update."""

    def record_exception(self, _exc: BaseException) -> None:
        """Accept and discard an exception record."""

    # No __enter__ / __exit__ on the no-op span: the library reaches
    # every span through the outer ``trace_span`` ``@contextmanager``,
    # so direct ``with span:`` use is not a supported path.


class _NoopTracer:
    """Null-object tracer: every span is a :class:`_NoopSpan`."""

    @contextmanager
    def start_as_current_span(self, _name: str) -> Any:
        """Yield a :class:`_NoopSpan` for use as a context manager."""
        yield _NoopSpan()


class _NoopCounter:
    """Null-object counter: every ``add`` is silently dropped."""

    def add(
        self, _amount: int, _attributes: dict[str, Any] | None = None
    ) -> None:
        """Accept and discard a counter increment."""


class _NoopHistogram:
    """Null-object histogram: every ``record`` is silently dropped."""

    def record(
        self, _value: float, _attributes: dict[str, Any] | None = None
    ) -> None:
        """Accept and discard a histogram observation."""


class _NoopMeter:
    """Null-object meter: every instrument is a stub."""

    def create_counter(self, *_args: Any, **_kwargs: Any) -> _NoopCounter:
        """Return a no-op counter, ignoring name / unit / description kwargs."""
        return _NoopCounter()

    def create_histogram(self, *_args: Any, **_kwargs: Any) -> _NoopHistogram:
        """Return a no-op histogram, ignoring name / unit / description kwargs."""
        return _NoopHistogram()


def get_tracer() -> Any:
    """Return the ``camt053`` tracer, or a no-op stub when OTel is absent.

    Idempotent and cheap to call repeatedly. The returned object
    exposes the subset of the OpenTelemetry API the camt053 service
    facade uses; consumers should not depend on it being a true OTel
    ``Tracer`` instance unless :func:`is_telemetry_available` is
    ``True``.
    """
    if not _OTEL_AVAILABLE:
        return _NoopTracer()
    return _otel_trace.get_tracer(  # pragma: no cover - OTel-only branch
        "camt053"
    )


def get_meter() -> Any:
    """Return the ``camt053`` meter, or a no-op stub when OTel is absent.

    Same contract as :func:`get_tracer`: stable subset, idempotent,
    cheap.
    """
    if not _OTEL_AVAILABLE:
        return _NoopMeter()
    return _otel_metrics.get_meter(  # pragma: no cover - OTel-only branch
        "camt053"
    )


@contextmanager
def trace_span(name: str) -> Any:
    """Open a span as the current span for the duration of the block.

    Use as a context manager around any operation worth tracing::

        with telemetry.trace_span(telemetry.SPAN_PARSE) as span:
            span.set_attribute("camt.msg_id", redacted_msg_id)
            result = expensive_parse()

    When OTel is absent the yielded object is a :class:`_NoopSpan`,
    so the ``set_attribute`` / ``set_status`` calls have zero cost.
    """
    tracer = get_tracer()
    with tracer.start_as_current_span(name) as span:
        yield span


# Module-level metric instruments. Created lazily on first use so
# the OTel SDK (if installed) doesn't get pulled in at import time
# unless someone actually emits a metric.
_REQUESTS_COUNTER: Any | None = None
_ERRORS_COUNTER: Any | None = None
_DURATION_HISTOGRAM: Any | None = None


def _requests_counter() -> Any:
    """Return the (lazily created) requests counter."""
    global _REQUESTS_COUNTER
    if _REQUESTS_COUNTER is None:
        _REQUESTS_COUNTER = get_meter().create_counter(
            METRIC_REQUESTS,
            unit="1",
            description=(
                "Count of camt053 service operations, "
                "labelled by op and status."
            ),
        )
    return _REQUESTS_COUNTER


def _errors_counter() -> Any:
    """Return the (lazily created) errors counter."""
    global _ERRORS_COUNTER
    if _ERRORS_COUNTER is None:
        _ERRORS_COUNTER = get_meter().create_counter(
            METRIC_ERRORS,
            unit="1",
            description=(
                "Count of failed camt053 service operations, "
                "labelled by op and error kind."
            ),
        )
    return _ERRORS_COUNTER


def _duration_histogram() -> Any:
    """Return the (lazily created) duration histogram."""
    global _DURATION_HISTOGRAM
    if _DURATION_HISTOGRAM is None:
        _DURATION_HISTOGRAM = get_meter().create_histogram(
            METRIC_DURATION,
            unit="s",
            description=("Wall-clock duration of camt053 service operations."),
        )
    return _DURATION_HISTOGRAM


def record_request(op: str, status: str = "ok") -> None:
    """Increment the requests counter for one ``op`` with one ``status``.

    Args:
        op: Short stable operation label (e.g. ``"parse"``,
            ``"validate"``, ``"reverse"``).
        status: ``"ok"`` (default) or ``"error"``. A separate
            :func:`record_error` is preferred when you also want to
            label by error kind.
    """
    _requests_counter().add(1, {"op": op, "status": status})


def record_error(op: str, kind: str) -> None:
    """Increment the errors counter for one ``op`` and ``kind``.

    Args:
        op: Short stable operation label.
        kind: Short stable error kind (e.g. the exception class name
            like ``"StatementParseError"`` or a domain-specific code
            like ``"UNSTRUCTURED_ONLY_ADDRESS"``).
    """
    _errors_counter().add(1, {"op": op, "kind": kind})


def record_duration(op: str, seconds: float) -> None:
    """Record one observation of an ``op`` taking ``seconds``.

    Args:
        op: Short stable operation label.
        seconds: Elapsed wall-clock seconds (float). Pair with
            :func:`time.perf_counter` for accurate timing.
    """
    _duration_histogram().record(seconds, {"op": op})


@contextmanager
def measure(op: str) -> Any:
    """Context manager that emits a span + request + duration + error.

    Combines :func:`trace_span`, :func:`record_request` (status =
    ``"ok"`` on clean exit, ``"error"`` otherwise),
    :func:`record_duration`, and :func:`record_error` (with the
    exception class name as the kind) so call sites stay one-liner::

        with telemetry.measure("parse"):
            return services.parse_statement(xml)

    Re-raises any exception unchanged after recording it.
    """
    span_name = f"camt053.{op}"
    start = time.perf_counter()
    status = "ok"
    error_kind: str | None = None
    try:
        with trace_span(span_name) as span:
            yield span
    except BaseException as exc:
        status = "error"
        error_kind = type(exc).__name__
        raise
    finally:
        elapsed = time.perf_counter() - start
        record_request(op, status)
        record_duration(op, elapsed)
        if error_kind is not None:
            record_error(op, error_kind)


def safe_span_attribute(key: str, value: Any) -> Any:
    """Return ``value`` with PII redacted per the key's sensitivity.

    Thin wrapper around :func:`camt053.logging.redact_value` so span
    attributes use the same redaction rules as log context. Use
    before calling ``span.set_attribute(key, value)``::

        span.set_attribute(
            "camt.account_iban",
            telemetry.safe_span_attribute(
                "account_iban", account.iban
            ),
        )
    """
    return redact_value(key, value)
